server:
  port: 8082
spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: wallet-service
              uri: lb://WALLET-SERVICE
              predicates:
                - Path=/wallet/**
            - id: identity-service
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/auth/**
            - id: Investment-service
              uri: lb://INVESTMENT-SERVICE
              predicates:
                - Path=/investment/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 10
                    redis-rate-limiter.requestedTokens: 5
                    key-resolver: "#{@userKeyResolver}"


eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/